### ISSUE TITLE
Didn't find class "com.esafirm.imagepicker.helper.ImagePickerFileProvider"

### ISSUE THREAD

**Issue by foxbamboo** [LintraMax/SourceAFIS-Android#1]
When apk starts, crash happens, and logcat says: Didn't find class 
 com.esafirm.imagepicker.helper.ImagePickerFileProvider"

Thanks for help!

**Comment by wilson-ong** [comment]
did you add the dependencies correctly?

https://github.com/esafirm/android-image-picker#download-

**Comment by wilson-ong** [comment]
What is your compileSDK version?

**Comment by wilson-ong** [comment]
v3.10.0 should have fixed this issue.
